### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by coderschoolreview** [trangvang/2flicks#1]
Hello! Thank you for submitting the second homework for CoderSchool React Class <g-emoji class="g-emoji" alias="tada" fallback-src="https://assets-cdn.github.com/images/icons/emoji/unicode/1f389.png" style="box-sizing: border-box; font-family: &quot;Apple Color Emoji&quot;, &quot;Segoe UI&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 18px; font-weight: 400; line-height: 20px; vertical-align: middle; margin-right: 3px;">🎉</g-emoji>! The main focus of this assignment was to introduce you to working with React Native, rendering items in a FlatList, and dealing with navigation.

### Great <g-emoji class="g-emoji" alias="sparkles" fallback-src="https://assets-cdn.github.com/images/icons/emoji/unicode/2728.png" style="box-sizing: border-box; font-family: &quot;Apple Color Emoji&quot;, &quot;Segoe UI&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 18px; font-weight: 400; line-height: 20px; vertical-align: middle; margin-right: 3px;">✨</g-emoji>

*   Really clean code! This is very good, didn't have to change many things in here.
*  Good job catching the errors when fetching movies in `componentWillMount` 

### Not so great yet <g-emoji class="g-emoji" alias="triangular_flag_on_post" fallback-src="https://assets-cdn.github.com/images/icons/emoji/unicode/1f6a9.png" style="box-sizing: border-box; font-family: &quot;Apple Color Emoji&quot;, &quot;Segoe UI&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 18px; font-weight: 400; line-height: 20px; vertical-align: middle; margin-right: 3px;">🚩</g-emoji>

* Do not leave `console.log` in the code :)
*   `props` is the named of properties given to your component. I suggest not creating another variable called `props`. For example:

```jsx
// const props = this.props.navigation.state.params;
const navigationParams = this.props.navigation.state.params;
```

Or

``` jsx
// const props = this.props.movie (don't do that)
```

* Consider using `eslint` to spot unused imports and have consistent code quality across your code. We haven't had a dedicated time to do this, so it's mostly our fault. You can install it really easily by typing

``` bash
yarn add -D eslint
eslint --init
```

*   I recommend chosing the guidelines from a popular company like Airbnb or Google. Then you can override some specific rules you don't like. Take a look at the `.eslintrc.js` file in my **Suggestions** for example of how to do that.

* * *

Good assignment overall 👏👏 You understand how to use the navigation, and pass informations to new screens, which was the goal ✅

If there's anything unclear with the feedback given here, please let us know!

**Comment by Tketa** [comment]
Oups sorry @trangvang this was for Khoa, I made a mistake. Can you delete this issue?

**Comment by trangvang** [comment]
Hi Jenemy, how I can delete issue? I don't find any action or tab to delete :|.
